services:
  auth-db:
    image: mariadb:latest
    container_name: auth-db
    env_file:
      - ./databases/auth/.env
    volumes:
      - auth_data:/var/lib/mysql
      - ./databases/auth/sql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      - shrp

  adminer:
    image: adminer
    container_name: adminer
    env_file:
      - ./databases/adminer/.env
    ports:
      - 8080:8080
    networks:
      - shrp

  bet-db:
    image: mariadb:latest
    container_name: bet-db
    env_file:
      - ./databases/bet/.env
    volumes:
      - bet_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - shrp

  bet-service:
    build:
      context: ./services/bet
      dockerfile: Dockerfile
    container_name: bet-service
    ports:
      - "3000:3000"
    depends_on:
      bet-db:
        condition: service_started
    volumes:
      - ./services/bet:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - shrp
volumes:
  auth_data:
  bet_data:
networks:
  shrp:
    driver: bridge
