services:
  auth-db:
    image: mariadb:latest
    container_name: auth-db
    env_file:
      - ./databases/auth/.env
    volumes:
      - auth_data:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - shrp

  adminer:
    image: adminer
    container_name: adminer
    env_file:
      - ./databases/adminer/.env
    ports:
      - 8081:8080
    networks:
      - shrp

  auth-service:
    image: auth-service
    container_name: auth-service
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    env_file:
      - ./services/auth/.env
    ports:
      - 3000:3000
    depends_on:
      - auth-db
    networks:
      - shrp

  bet-db:
    image: mariadb:latest
    container_name: bet-db
    env_file:
      - ./databases/bet/.env
    volumes:
      - bet_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - shrp

  bet-service:
    build:
      context: ./services/bet
      dockerfile: Dockerfile
    container_name: bet-service
    ports:
      - "3001:3001"
    depends_on:
      bet-db:
        condition: service_started
    volumes:
      - ./services/bet:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - shrp

  deal-db:
    image: mysql:latest
    container_name: deal-db
    env_file:
      - ./databases/deal/.env
    volumes:
      - deal_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - shrp

  deal-service:
    build:
      context: ./services/deal
      dockerfile: Dockerfile
    container_name: deal-service
    ports:
      - "8080:8080"
    depends_on:
      deal-db:
        condition: service_started
    networks:
      - shrp
volumes:
  auth_data:
  bet_data:
  deal_data:
networks:
  shrp:
    driver: bridge
