services:
  auth-db:
    image: mariadb:latest
    container_name: auth-db
    env_file:
      - ./databases/auth/.env
    volumes:
      - auth_data:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - shrp

  adminer:
    image: adminer
    container_name: adminer
    env_file:
      - ./databases/adminer/.env
    ports:
      - 8080:8080
    networks:
      - shrp

  auth-service:
    image: auth-service
    container_name: auth-service
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    env_file:
      - ./services/auth/.env
    ports:
      - 3000:3000
    depends_on:
      - auth-db
    networks:
      - shrp

volumes:
  auth_data:
networks:
  shrp:
    driver: bridge
